.TH neix 1 "22nd July 2020" "v0.1.0" "neix man page"

.SH NAME
.B neix
- RSS/Atom feed reader for your terminal.

.SH SYNOPSIS
.B neix
is an terminal feed reader for all common RSS/Atom feeds on the web out there.

.SH DESCRIPTION
.B neix
is an terminal feed reader for all common RSS/Atom feeds on the web out there.
It will protect your privacy with a nice looking TUI and with an nice performance.

.SH OPTIONS
.B -v
	Prints the installed version of *neix* and exits.

.SH AUTHORS
Maintained by Tom Schwarz<thomasschwarz96@web.de>, who is assisted by
other open source contributors. For more informations about 
.B neix
development see https://github.com/tomschwarz/neix.

.SH SEE ALSO
.B ncurses(1),
.B curl(1)

